name: Python Multi-Service CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        service: [user-service, loan-service, account-service]
    
    environment: ${{ matrix.service }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f backend/requirements.txt ]; then 
          pip install -r backend/requirements.txt; 
        fi

    - name: Create .env file for ${{ matrix.service }}
      run: |
        cd backend/${{ matrix.service }}
        touch .env
        echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
        echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
        echo "ALGORITHM=${{ secrets.ALGORITHM }}" >> .env
        echo "ACCESS_TOKEN_EXPIRES_MINUTES=${{ secrets.ACCESS_TOKEN_EXPIRES_MINUTES }}" >> .env
        echo "MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}" >> .env
        echo "ROLE_ADMIN=${{ secrets.ROLE_ADMIN }}" >> .env
        echo "ROLE_USER=${{ secrets.ROLE_USER }}" >> .env
        
        if [ "${{ matrix.service }}" == "loan-service" ]; then
          echo "ACCOUNT_SERVICE_URL=${{ secrets.ACCOUNT_SERVICE_URL }}" >> .env
        fi

    - name: Lint with flake8
      run: |
        flake8 backend/${{ matrix.service }} --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 backend/${{ matrix.service }} --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        ALGORITHM: ${{ secrets.ALGORITHM }}
        PYTHONPATH: ${{ github.workspace }}/backend/${{ matrix.service }}
      run: |
        cd backend/${{ matrix.service }}

        if [ "${{ matrix.service }}" == "user-service" ]; then
          pytest user_tests -v
        elif [ "${{ matrix.service }}" == "loan-service" ]; then
          pytest loan_tests -v
        elif [ "${{ matrix.service }}" == "account-service" ]; then
          pytest account_tests -v
        fi
